# Generated by Django 4.0 on 2024-03-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_column='user_id')),
                ('order_id', models.IntegerField(db_column='order_id')),
                ('address', models.CharField(db_column='address', max_length=255)),
                ('date', models.DateTimeField(db_column='date')),
                ('status', models.CharField(db_column='status', max_length=255)),
            ],
            options={
                'db_table': 'shipment',
            },
        ),
    ]
