# Generated by Django 4.0 on 2024-03-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_shipment_ship_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='ship_fee',
            field=models.FloatField(db_column='ship_fee', default=20.0),
        ),
    ]
