# Generated by Django 4.0 on 2024-03-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category Name')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'category_mobile',
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('brand', models.CharField(max_length=255, verbose_name='Brand')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='mobiles/')),
                ('categories', models.ManyToManyField(related_name='mobiles', to='mobile.Category_Mobile', verbose_name='Categories')),
            ],
        ),
    ]
