# Generated by Django 4.0 on 2024-03-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category_Mobile',
        ),
    ]
