# Generated by Django 4.0 on 2024-03-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_column='user_id')),
                ('order_id', models.IntegerField(db_column='order_id')),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, max_digits=10)),
                ('method', models.CharField(db_column='method', max_length=255)),
                ('date', models.DateTimeField(db_column='date')),
            ],
            options={
                'db_table': 'payment_order',
            },
        ),
    ]
