# Generated by Django 4.0 on 2024-03-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(db_column='full_name', max_length=255)),
                ('email', models.CharField(db_column='email', max_length=255, unique=True)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('phone', models.CharField(db_column='phone', max_length=255)),
                ('address', models.CharField(db_column='address', max_length=255)),
                ('role', models.CharField(db_column='role', max_length=30)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
