# Generated by Django 4.0 on 2024-03-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='local_user',
        ),
    ]
