# Generated by Django 4.0 on 2024-01-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='siuubook.jpg', upload_to='book\\static'),
        ),
    ]
