# Generated by Django 4.0 on 2024-02-01 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_category_book_categries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='categries',
            new_name='categories',
        ),
    ]
