# Generated by Django 4.0 on 2024-03-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cart_clothe_cart_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default='available', max_length=255, verbose_name='Status'),
        ),
    ]
